name: Build and Deploy App

on:
  push:
    branches: ['develop']
  pull_request:
    branches: ['develop']

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: capton007/backend-logistics:dev

      - name: Push to Docker Hub
        run: |
          docker login -u capton007 -p ${{ secrets.DOCKER_TOKEN }}
          docker push capton007/backend-logistics:dev
          docker logout
