name: Build and Deploy App

on:
  push:
    branches: ['develop', 'main']
  pull_request:
    branches: ['develop']

jobs:
  # -------------------------
  # DEVELOP → Docker + Render
  # -------------------------
  build-develop:
    if: github.ref == 'refs/heads/develop'
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - name: Build Docker image
        uses: docker/build-push-action@v5
        with:
          context: .
          file: ./Dockerfile
          push: false
          tags: capton007/backend-logistics:dev

      - name: Push to Docker Hub
        run: |
          docker login -u capton007 -p ${{ secrets.DOCKER_TOKEN }}
          docker push capton007/backend-logistics:dev
          docker logout

  deploy-develop:
    if: github.ref == 'refs/heads/develop'
    needs: build-develop
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Trigger deployment on Render
        env:
          deploy_url: ${{ secrets.RENDER_DEPLOY_HOOK_URL }}
        run: curl "$deploy_url"

  # -------------------------
  # MAIN → Deploy branch for cPanel Git
  # -------------------------
  build-main:
    if: github.ref == 'refs/heads/main'
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 18

      - name: Install dependencies
        run: npm ci

      - name: Build NestJS app
        run: npm run build

      - name: Prepare deployment branch
        run: |
          mkdir deploy
          cp -r dist package.json package-lock.json deploy/
          cd deploy
          git init
          git config user.name "GitHub Actions"
          git config user.email "actions@github.com"
          git checkout -b deploy-cpanel
          git add .
          git commit -m "Deploy build from $GITHUB_SHA"
          git remote add origin https://github.com/${{ github.repository }}.git
          git push --force origin deploy-cpanel
